[[section_cli]]
== CLI

=== Generate

For this tool, the `creatorly.yml` file must be in the root directory of the template project. This file contains the configuration for the template project. Each of the key-value pairs within the key `placeholders` in the `creatorly.yml` file can be used as a placeholder variable in all files and file paths. Each placeholder variable must be enclosed in `{{ creatorly.<placeholder_name> }}` in the files. As link:https://shopify.github.io/liquid/[Shopify-Liquid] is used as the template engine, the detailed rules can be found on the website.

Below is an example of a `creatorly.yml` file:

[source,yml]
----
placeholders:
    project_name: "My Template Project"
----

Below is an example of a `README.md` file that uses the `project_name` variable from the `creatorly.yml` file:

[source,md]
----
# Documentation {{ creatorly.project_name }}
----

This then becomes after this tool is executed:

[source,md]
----
# Documentation My Template Project
----

TIP: Not only the content of the files can be rendered, but also the file name itself. For this purpose, a `{{ }}` block must be used in the file name as well as in the content of the file. Example the file `{{ creatorly.project_name }}.md` will be rendered to `My Template Project.md`, if the `project_name` variable is set to `My Template Project`.

==== Use the CLI

To generate a new project from a template, the following command can be executed:

===== Local template project

[source,bash]
----
    creatorly generate local --template-path <template_path> --destination-path <destination_path>
----

===== Remote template project (git)

[source,bash]
----
    creatorly generate git --remote-path <remote_path> --branch <branch>  --destination-path <destination_path>
----


TIP: If the git repository has submodules, they will be also cloned. If you want to use a private repository, then you need to make sure that you have access to the repo with the local git commands.

